apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: instana-agent
  name: instana-agent
spec:
  ports:
    - name: "42699"
      port: 42699
      targetPort: 42699
    - name: "4317"
      port: 4317
      targetPort: 4317
    - name: "4318"
      port: 4318
      targetPort: 4318
  selector:
    io.kompose.service: instana-agent
status:
  loadBalancer: {}
